# Generated by Django 4.2.20 on 2026-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dify_message_id', models.CharField(max_length=100, unique=True, verbose_name='Dify消息ID')),
                ('query_text', models.TextField(verbose_name='用户提问')),
                ('answer_text', models.TextField(verbose_name='AI回答')),
                ('stage_key', models.CharField(blank=True, default='', max_length=100, verbose_name='所处阶段')),
                ('message_index', models.IntegerField(default=0, verbose_name='消息序号')),
                ('token_count', models.IntegerField(default=0, verbose_name='Token消耗')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='响应耗时(ms)')),
                ('inputs_data', models.TextField(default='{}', verbose_name='输入变量(JSON)')),
                ('files_data', models.TextField(default='[]', verbose_name='附件信息(JSON)')),
                ('feedback', models.CharField(blank=True, default='', max_length=20, verbose_name='用户反馈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '对话日志',
                'verbose_name_plural': '对话日志',
                'db_table': 'chat_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dify_conversation_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Dify会话ID')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='会话标题')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('abandoned', '已放弃')], default='active', max_length=20, verbose_name='状态')),
                ('current_stage', models.CharField(blank=True, default='', max_length=100, verbose_name='当前阶段')),
                ('completed_stages', models.TextField(default='[]', verbose_name='已完成阶段(JSON)')),
                ('total_messages', models.IntegerField(default=0, verbose_name='总消息数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会话记录',
                'verbose_name_plural': '会话记录',
                'db_table': 'conversation_sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
