# Generated by Django 4.2.20 on 2026-05-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dify_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dify_integration.learningworkflow', verbose_name='教学流程'),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='chat_logs.conversationsession', verbose_name='所属会话'),
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['session'], name='chat_logs_session_35922e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['stage_key'], name='chat_logs_stage_k_686542_idx'),
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['created_at'], name='chat_logs_created_00b4c5_idx'),
        ),
    ]
