# Generated by Django 4.2.20 on 2026-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息数')),
                ('time_spent_seconds', models.IntegerField(default=0, verbose_name='耗时(秒)')),
                ('stage_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='阶段得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评分明细',
                'verbose_name_plural': '评分明细',
                'db_table': 'score_details',
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_stage_completion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='阶段完成度')),
                ('auto_sequence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='流程遵循度')),
                ('auto_time_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='时间投入')),
                ('auto_engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='参与度')),
                ('auto_total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='自动总分')),
                ('teacher_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='教师评分')),
                ('teacher_comment', models.TextField(blank=True, default='', verbose_name='教师评语')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('status', models.CharField(choices=[('pending_review', '待复核'), ('reviewed', '已复核'), ('finalized', '已确认')], default='pending_review', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生评分',
                'verbose_name_plural': '学生评分',
                'db_table': 'student_scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
