# Generated by Django 4.2.20 on 2026-05-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoring', '0001_initial'),
        ('dify_integration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_logs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scores', to=settings.AUTH_USER_MODEL, verbose_name='复核教师'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='chat_logs.conversationsession', verbose_name='关联会话'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='dify_integration.learningworkflow', verbose_name='教学流程'),
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='scoring.studentscore', verbose_name='评分记录'),
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dify_integration.workflowstage', verbose_name='流程阶段'),
        ),
    ]
