# Generated by Django 4.2.20 on 2026-05-23 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifyUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dify_user_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Dify用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name': 'Dify用户映射',
                'verbose_name_plural': 'Dify用户映射',
                'db_table': 'dify_user_mappings',
            },
        ),
        migrations.CreateModel(
            name='LearningWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='流程名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('dify_app_id', models.CharField(blank=True, max_length=100, verbose_name='Dify应用ID')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教学流程',
                'verbose_name_plural': '教学流程',
                'db_table': 'learning_workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='阶段名称')),
                ('stage_key', models.CharField(max_length=100, verbose_name='阶段标识')),
                ('order_index', models.IntegerField(verbose_name='顺序索引')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('expected_min_messages', models.IntegerField(default=1, verbose_name='预期最少消息数')),
                ('expected_min_minutes', models.IntegerField(default=2, verbose_name='预期最少耗时(分)')),
                ('weight', models.DecimalField(decimal_places=2, default=0.25, max_digits=3, verbose_name='评分权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='dify_integration.learningworkflow', verbose_name='所属流程')),
            ],
            options={
                'verbose_name': '流程阶段',
                'verbose_name_plural': '流程阶段',
                'db_table': 'workflow_stages',
                'ordering': ['order_index'],
            },
        ),
    ]
