# Generated by Django 4.2.20 on 2026-05-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dify_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningworkflow',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL, verbose_name='所属教师'),
        ),
        migrations.AddField(
            model_name='difyusermapping',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dify_mapping', to=settings.AUTH_USER_MODEL, verbose_name='系统用户'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstage',
            unique_together={('workflow', 'stage_key'), ('workflow', 'order_index')},
        ),
    ]
