# Generated by Django 4.2.30 on 2026-05-27 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dify_integration', '0003_difyconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningworkflow',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to=settings.AUTH_USER_MODEL, verbose_name='所属教师'),
        ),
    ]
